class LeaderboardData:
    "Store of unchanging dictionary linking ids to matchtypes etc."

    def __init__(self) -> None:

        self.leaderboard = (

{'factions': [],
 'info': 'NORMAL',
 'leaderboardRegions': [],
 'leaderboards': [{'id': 0,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 0,
                                       'race_id': 0,
                                       'statgroup_type': 1}],
                   'name': 'CustomAmerican'},
                  {'id': 1,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 0,
                                       'race_id': 1,
                                       'statgroup_type': 1}],
                   'name': 'CustomWehrmacht'},
                  {'id': 2,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 0,
                                       'race_id': 2,
                                       'statgroup_type': 1}],
                   'name': 'CustomBritish'},
                  {'id': 3,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 0,
                                       'race_id': 3,
                                       'statgroup_type': 1}],
                   'name': 'CustomPanzer'},
                  {'id': 4,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 1,
                                       'race_id': 0,
                                       'statgroup_type': 1}],
                   'name': '1v1American'},
                  {'id': 5,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 1,
                                       'race_id': 1,
                                       'statgroup_type': 1}],
                   'name': '1v1Wehrmacht'},
                  {'id': 6,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 1,
                                       'race_id': 2,
                                       'statgroup_type': 1}],
                   'name': '1v1British'},
                  {'id': 7,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 1,
                                       'race_id': 3,
                                       'statgroup_type': 1}],
                   'name': '1v1Panzer'},
                  {'id': 8,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 2,
                                       'race_id': 0,
                                       'statgroup_type': 1}],
                   'name': '2v2American'},
                  {'id': 9,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 2,
                                       'race_id': 1,
                                       'statgroup_type': 1}],
                   'name': '2v2Wehrmacht'},
                  {'id': 10,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 2,
                                       'race_id': 2,
                                       'statgroup_type': 1}],
                   'name': '2v2British'},
                  {'id': 11,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 2,
                                       'race_id': 3,
                                       'statgroup_type': 1}],
                   'name': '2v2Panzer'},
                  {'id': 12,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 3,
                                       'race_id': 0,
                                       'statgroup_type': 1}],
                   'name': '3v3American'},
                  {'id': 13,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 3,
                                       'race_id': 1,
                                       'statgroup_type': 1}],
                   'name': '3v3Wehrmacht'},
                  {'id': 14,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 3,
                                       'race_id': 2,
                                       'statgroup_type': 1}],
                   'name': '3v3British'},
                  {'id': 15,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 3,
                                       'race_id': 3,
                                       'statgroup_type': 1}],
                   'name': '3v3Panzer'},
                  {'id': 16,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 4,
                                       'race_id': 0,
                                       'statgroup_type': 1}],
                   'name': '4v4American'},
                  {'id': 17,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 4,
                                       'race_id': 1,
                                       'statgroup_type': 1}],
                   'name': '4v4Wehrmacht'},
                  {'id': 18,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 4,
                                       'race_id': 2,
                                       'statgroup_type': 1}],
                   'name': '4v4British'},
                  {'id': 19,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 4,
                                       'race_id': 3,
                                       'statgroup_type': 1}],
                   'name': '4v4Panzer'},
                  {'id': 20,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 5,
                                       'race_id': 0,
                                       'statgroup_type': 2},
                                      {'matchtype_id': 5,
                                       'race_id': 2,
                                       'statgroup_type': 2}],
                   'name': '2v2TeamAllies'},
                  {'id': 21,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 5,
                                       'race_id': 1,
                                       'statgroup_type': 2},
                                      {'matchtype_id': 5,
                                       'race_id': 3,
                                       'statgroup_type': 2}],
                   'name': '2v2TeamAxis'},
                  {'id': 22,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 6,
                                       'race_id': 0,
                                       'statgroup_type': 3},
                                      {'matchtype_id': 6,
                                       'race_id': 2,
                                       'statgroup_type': 3}],
                   'name': '3v3TeamAllies'},
                  {'id': 23,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 6,
                                       'race_id': 1,
                                       'statgroup_type': 3},
                                      {'matchtype_id': 6,
                                       'race_id': 3,
                                       'statgroup_type': 3}],
                   'name': '3v3TeamAxis'},
                  {'id': 24,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 7,
                                       'race_id': 0,
                                       'statgroup_type': 4},
                                      {'matchtype_id': 7,
                                       'race_id': 2,
                                       'statgroup_type': 4}],
                   'name': '4v4TeamAllies'},
                  {'id': 25,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 7,
                                       'race_id': 1,
                                       'statgroup_type': 4},
                                      {'matchtype_id': 7,
                                       'race_id': 3,
                                       'statgroup_type': 4}],
                   'name': '4v4TeamAxis'},
                  {'id': 26,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 8,
                                       'race_id': 0,
                                       'statgroup_type': 1}],
                   'name': '2v2AssaultAmerican'},
                  {'id': 27,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 8,
                                       'race_id': 1,
                                       'statgroup_type': 1}],
                   'name': '2v2AssaultWehrmacht'},
                  {'id': 28,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 8,
                                       'race_id': 2,
                                       'statgroup_type': 1}],
                   'name': '2v2AssaultBritish'},
                  {'id': 29,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 8,
                                       'race_id': 3,
                                       'statgroup_type': 1}],
                   'name': '2v2AssaultPanzer'},
                  {'id': 30,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 9,
                                       'race_id': 0,
                                       'statgroup_type': 2},
                                      {'matchtype_id': 9,
                                       'race_id': 2,
                                       'statgroup_type': 2}],
                   'name': '2v2AssaultTeamAllies'},
                  {'id': 31,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 9,
                                       'race_id': 1,
                                       'statgroup_type': 2},
                                      {'matchtype_id': 9,
                                       'race_id': 3,
                                       'statgroup_type': 2}],
                   'name': '2v2AssaultTeamAxis'},
                  {'id': 32,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 10,
                                       'race_id': 0,
                                       'statgroup_type': 3},
                                      {'matchtype_id': 10,
                                       'race_id': 2,
                                       'statgroup_type': 3}],
                   'name': '3v3AssaultTeamAllies'},
                  {'id': 33,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 10,
                                       'race_id': 1,
                                       'statgroup_type': 3},
                                      {'matchtype_id': 10,
                                       'race_id': 3,
                                       'statgroup_type': 3}],
                   'name': '3v3AssaultTeamAxis'},
                  {'id': 34,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 11,
                                       'race_id': 0,
                                       'statgroup_type': 1}],
                   'name': '2v2PanzerkriegAmerican'},
                  {'id': 35,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 11,
                                       'race_id': 1,
                                       'statgroup_type': 1}],
                   'name': '2v2PanzerkriegWehrmacht'},
                  {'id': 36,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 11,
                                       'race_id': 2,
                                       'statgroup_type': 1}],
                   'name': '2v2PanzerkriegBritish'},
                  {'id': 37,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 11,
                                       'race_id': 3,
                                       'statgroup_type': 1}],
                   'name': '2v2PanzerkriegPanzer'},
                  {'id': 38,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 12,
                                       'race_id': 0,
                                       'statgroup_type': 2},
                                      {'matchtype_id': 12,
                                       'race_id': 2,
                                       'statgroup_type': 2}],
                   'name': '2v2PanzerkriegTeamAllies'},
                  {'id': 39,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 12,
                                       'race_id': 1,
                                       'statgroup_type': 2},
                                      {'matchtype_id': 12,
                                       'race_id': 3,
                                       'statgroup_type': 2}],
                   'name': '2v2PanzerkriegTeamAxis'},
                  {'id': 40,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 13,
                                       'race_id': 0,
                                       'statgroup_type': 3},
                                      {'matchtype_id': 13,
                                       'race_id': 2,
                                       'statgroup_type': 3}],
                   'name': '3v3PanzerkriegTeamAllies'},
                  {'id': 41,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 13,
                                       'race_id': 1,
                                       'statgroup_type': 3},
                                      {'matchtype_id': 13,
                                       'race_id': 3,
                                       'statgroup_type': 3}],
                   'name': '3v3PanzerkriegTeamAxis'},
                  {'id': 42,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 14,
                                       'race_id': 0,
                                       'statgroup_type': 0}],
                   'name': 'CompStompAmerican'},
                  {'id': 43,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 14,
                                       'race_id': 1,
                                       'statgroup_type': 0}],
                   'name': 'CompStompWehrmacht'},
                  {'id': 44,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 14,
                                       'race_id': 2,
                                       'statgroup_type': 0}],
                   'name': 'CompStompBritish'},
                  {'id': 45,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 14,
                                       'race_id': 3,
                                       'statgroup_type': 0}],
                   'name': 'CompStompPanzer'},
                  {'id': 46,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 15,
                                       'race_id': 0,
                                       'statgroup_type': 0}],
                   'name': 'AssaultAmerican'},
                  {'id': 47,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 15,
                                       'race_id': 1,
                                       'statgroup_type': 0}],
                   'name': 'AssaultWehrmacht'},
                  {'id': 48,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 15,
                                       'race_id': 2,
                                       'statgroup_type': 0}],
                   'name': 'AssaultBritish'},
                  {'id': 49,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 15,
                                       'race_id': 3,
                                       'statgroup_type': 0}],
                   'name': 'AssaultPanzer'},
                  {'id': 50,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 16,
                                       'race_id': 0,
                                       'statgroup_type': 0}],
                   'name': 'PanzerKriegAmerican'},
                  {'id': 51,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 16,
                                       'race_id': 1,
                                       'statgroup_type': 0}],
                   'name': 'PanzerKriegWehrmacht'},
                  {'id': 52,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 16,
                                       'race_id': 2,
                                       'statgroup_type': 0}],
                   'name': 'PanzerKriegBritish'},
                  {'id': 53,
                   'isranked': 1,
                   'leaderboardmap': [{'matchtype_id': 16,
                                       'race_id': 3,
                                       'statgroup_type': 0}],
                   'name': 'PanzerKriegPanzer'},
                  {'id': 54,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 17,
                                       'race_id': 0,
                                       'statgroup_type': 0}],
                   'name': 'StoneWallAmerican'},
                  {'id': 55,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 17,
                                       'race_id': 1,
                                       'statgroup_type': 0}],
                   'name': 'StoneWallWehrmacht'},
                  {'id': 56,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 17,
                                       'race_id': 2,
                                       'statgroup_type': 0}],
                   'name': 'StoneWallBritish'},
                  {'id': 57,
                   'isranked': 0,
                   'leaderboardmap': [{'matchtype_id': 17,
                                       'race_id': 3,
                                       'statgroup_type': 0}],
                   'name': 'StoneWallPanzer'}],
 'matchTypes': [{'id': 0, 'locstringid': -1, 'name': 'CUSTOM'},
                {'id': 1, 'locstringid': -1, 'name': '1V1'},
                {'id': 2, 'locstringid': -1, 'name': '2V2'},
                {'id': 3, 'locstringid': -1, 'name': '3V3'},
                {'id': 4, 'locstringid': -1, 'name': '4V4'},
                {'id': 5, 'locstringid': -1, 'name': 'TEAM_2v2'},
                {'id': 6, 'locstringid': -1, 'name': 'TEAM_3v3'},
                {'id': 7, 'locstringid': -1, 'name': 'TEAM_4v4'},
                {'id': 8, 'locstringid': -1, 'name': 'ASSAULT_2v2'},
                {'id': 9, 'locstringid': -1, 'name': 'ASSAULT_TEAM_2v2'},
                {'id': 10, 'locstringid': -1, 'name': 'ASSAULT_TEAM_3v3'},
                {'id': 11, 'locstringid': -1, 'name': 'PANZERKRIEG_2v2'},
                {'id': 12, 'locstringid': -1, 'name': 'PANZERKRIEG_TEAM_2v2'},
                {'id': 13, 'locstringid': -1, 'name': 'PANZERKRIEG_TEAM_3v3'},
                {'id': 14, 'locstringid': -1, 'name': 'COMPSTOMP'},
                {'id': 15, 'locstringid': -1, 'name': 'ASSAULT'},
                {'id': 16, 'locstringid': -1, 'name': 'PANZERKRIEG'},
                {'id': 17, 'locstringid': -1, 'name': 'STONEWALL'}],
 'message': '',
 'races': [{'faction_id': 0, 'id': 0, 'locstringid': -1, 'name': 'American'},
           {'faction_id': 1, 'id': 1, 'locstringid': -1, 'name': 'Wehrmacht'},
           {'faction_id': 0, 'id': 2, 'locstringid': -1, 'name': 'British'},
           {'faction_id': 1, 'id': 3, 'locstringid': -1, 'name': 'Panzer'}],
 'reason': '',
 'result': {'code': 0, 'message': 'SUCCESS'}})
